apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-pi
  namespace: apache-spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: apache-spark
  name: spark-pi
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "services", "persistentvolumeclaims"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-pi
  namespace: apache-spark
subjects:
- kind: ServiceAccount
  name: spark-pi
  namespace: apache-spark
roleRef:
  kind: Role
  name: spark-pi
  apiGroup: rbac.authorization.k8s.io
