apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata: 
  name: spark-pi
  namespace: apache-spark
spec:
  type: Python
  pythonVersion: "3"
  sparkVersion: "3.4.0"
  mode: cluster
  image: spark-pi:latest
  imagePullPolicy: Never
  mainApplicationFile: local:///app/main.py
  driver:
    cores: 1
    memory: "512m"
    serviceAccount: spark-pi-k8s-operator
  executor:
    instances: 1
    cores: 1
    memory: "512m"
    deleteOnTermination: True
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-pi-k8s-operator
  namespace: apache-spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: apache-spark
  name: spark-pi-k8s-operator
rules:
- apiGroups: [""]
  resources: ["pods", "configmaps", "services", "persistentvolumeclaims"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-pi-k8s-operator
  namespace: apache-spark
subjects:
- kind: ServiceAccount
  name: spark-pi-k8s-operator
  namespace: apache-spark
roleRef:
  kind: Role
  name: spark-pi-k8s-operator
  apiGroup: rbac.authorization.k8s.io
